POST http://localhost:10000/articles HTTP/1.1
content-type: application/json

{
    "Id": "3", 
    "Title": "Newly Created Post", 
    "desc": "The description for my new post", 
    "content": "my articles content" 
}